export const TOGGLE_TEST = 'TOGGLE_TEST';

export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';

export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_FAILURE = 'FETCH_TOPICS_FAILURE';

export const FETCH_ONE_ARTICLE_REQUEST = 'FETCH_ONE_ARTICLE_REQUEST';
export const FETCH_ONE_ARTICLE_SUCCESS = 'FETCH_ONE_ARTICLE_SUCCESS';
export const FETCH_ONE_ARTICLE_FAILURE = 'FETCH_ONE_ARTICLE_FAILURE';

export const POST_COMMENTS_REQUEST = 'POST_COMMENTS_REQUEST';
export const POST_COMMENTS_SUCCESS = 'POST_COMMENTS_SUCCESS';
export const POST_COMMENTS_FAILURE = 'POST_COMMENTS_FAILURE';

export const VOTE_COMMENTS_REQUEST = 'VOTE_COMMENTS_REQUEST';
export const VOTE_COMMENTS_SUCCESS = 'VOTE_COMMENTS_SUCCESS';
export const VOTE_COMMENTS_FAILURE = 'VOTE_COMMENTS_FAILURE';

export const VOTE_ARTICLES_REQUEST = 'VOTE_ARTICLES_REQUEST';
export const VOTE_ARTICLES_SUCCESS = 'VOTE_ARTICLES_SUCCESS';
export const VOTE_ARTICLES_FAILURE = 'VOTE_ARTICLES_FAILURE';

export const REMOVE_COMMENTS_REQUEST = 'REMOVE_COMMENTS_REQUEST';
export const REMOVE_COMMENTS_SUCCESS = 'REMOVE_COMMENTS_SUCCESS';
export const REMOVE_COMMENTS_FAILURE = 'REMOVE_COMMENTS_FAILURE';

export const FETCH_USERS_REQUEST = 'GET_USER_REQUEST';
export const FETCH_USERS_SUCCESS = 'GET_USER_SUCCESS';
export const FETCH_USERS_FAILURE = 'GET_USER_FAILURE';